version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: bank_app_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bank_app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - bankapp_network

volumes:
  pgdata:

networks:
  bankapp_network:
    driver: bridge
